openapi: 3.0.0
info:
  title: 在庫管理システム
  description: 実装で学ぶフルスタックWeb開発で作る「在庫管理システム」
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/inventory/products:
    get:
      summary: 商品一覧参照
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: "商品ID"
                      example: 1
                    name:
                      type: string
                      description: "商品名"
                      example: "コットン100%バックリボンティアードワンピース（黒）"
                    price:
                      type: number
                      description: "商品単価"
                      example: 6900
                    description:
                      type: string
                      description: "商品説明"
                      example: "大人の愛らしさを引き立てる、ナチュラルな風合い。リラックスxトレンドを楽しめる、上品なティアードワンピース。"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to fetch products"
    post:
      summary: 商品作成
      description: 新しい商品を作成します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "商品名"
                  example: "アソートフレアスカート"
                price:
                  type: number
                  description: "商品単価"
                  example: 6000
                description:
                  type: string
                  description: "商品説明"
                  example: "オトナも可愛くスタイルアップ！爽やかで印象に残る春スカート"
      responses:
        '201':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: "商品ID"
                    example: 1
                  name:
                    type: string
                    description: "商品名"
                    example: "アソートフレアスカート"
                  price:
                    type: number
                    description: "商品単価"
                    example: 6000
                  description:
                    type: string
                    description: "商品説明"
                    example: "オトナも可愛くスタイルアップ！爽やかで印象に残る春スカート"
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Invalid input data"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to create product"
  /api/inventory/products/{id}:
    get:
      summary: 商品参照
      parameters:
        - name: id
          in: path
          required: true
          description: "商品ID"
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: "商品ID"
                    example: 1
                  name:
                    type: string
                    description: "商品名"
                    example: "コットン100%バックリボンティアードワンピース（黒）"
                  price:
                    type: number
                    description: "商品単価"
                    example: 6900
                  description:
                    type: string
                    description: "商品説明"
                    example: "大人の愛らしさを引き立てる、ナチュラルな風合い。リラックスxトレンドを楽しめる、上品なティアードワンピース。"
        '404':
          description: Not Found - Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Product not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to fetch product details"
    delete:
      summary: 商品削除
      parameters:
        - name: id
          in: path
          required: true
          description: "商品ID"
          schema:
            type: number
            example: 1
      responses:
        '204':
          description: No Content - Product deleted successfully
        '404':
          description: Not Found - Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Product not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to delete product"
  /api/inventory/purchase:
    post:
      summary: 仕入れ登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                  description: "商品ID"
                  example: 1
                quantity:
                  type: number
                  description: "数量"
                  example: 400
      responses:
        '201':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Inventory created"
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "product_id and quantity are required"
        '404':
          description: Not Found - Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Product not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to create inventory"
  /api/inventory/sales:
    post:
      summary: 卸し登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                  description: "商品ID"
                  example: 1
                quantity:
                  type: number
                  description: "数量"
                  example: 400
      responses:
        '201':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Inventory created"
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "product_id and quantity are required"
        '404':
          description: Not Found - Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Product not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "エラーメッセージ"
                    example: "Failed to create inventory"
